name: Build ESP32 Neopixel Tetris
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    # https://github.com/espressif/esp-idf-ci-action
    - name: esp-idf build
      uses: espressif/esp-idf-ci-action@v1
      with:
        target: esp32s3
        path: './'
